### PR TITLE
Bump persona-php-client to >=3.1

### PR DESCRIPTION
**Pull request by camillef**
See https://github.com/talis/persona-php-client/releases for changes between 2.0 and 3.0

### CODE REVIEW

**Comment by rsinger** [comment]
Why not 3.1?

**Comment by markwallsgrove** [comment]
Surely there was a breaking change from 2 -> 3?

**Comment by camillef** [comment]
@markwallsgrove https://github.com/talis/persona-php-client/releases/tag/3.0 will that be a problem?

**Comment by markwallsgrove** [comment]
Yes, it will be a issue. `cacheBackend` is missing from the configuration.

```php
    protected function getPersonaClient()
    {
        if (!isset($this->personaClient))
        {
            $this->personaClient = new \Talis\Persona\Client\Tokens(array(
                'persona_host' => PERSONA_HOST,
                'persona_oauth_route' => PERSONA_OAUTH_ROUTE,
                'tokencache_redis_host' => PERSONA_TOKENCACHE_HOST,
                'tokencache_redis_port' => PERSONA_TOKENCACHE_PORT,
                'tokencache_redis_db' => PERSONA_TOKENCACHE_DB,
                'userAgent' => 'echo-php-client'
            ));
        }
        return $this->personaClient;
    }
```

**Comment by markwallsgrove** [comment]
Those attributes also look old.

**Comment by markwallsgrove** [comment]
@pads @robotrobot @rsinger should the echo-php-client use the configuration provided to store the cache in redis? i.e. `PERSONA_TOKENCACHE_HOST`, `PERSONA_TOKENCACHE_PORT` & `PERSONA_TOKENCACHE_DB`

**Comment by markwallsgrove** [comment]
I cannot see the harm in doing so as the data is well namespaced.

**Comment by camillef** [comment]
@markwallsgrove Something like that? Have no idea about versions... just doing what used to be in persona-php-client ...

**Comment by pads** [comment]
This change looks fine to me. Double check with @rgoj that this is OK as he is doing work on the persona-php-client currently. I don't think there will be any conflicts there though.

**Comment by camillef** [comment]
@pads Is @rgoj in today? This is a blocker for me as I'm working on https://github.com/talis/rl-app/pull/1161

**Comment by pads** [comment]
No he's not. I had a look at his story and he's not changing the Persona PHP client, he is bumping this client. He'll just have to bump again after this merge so :+1:

**Pull request merged**
